version: 0.0
os: linux
files:
  - source: / #인스턴스에 복사할 파일 또는 디렉토리 경로
    destination: /home/ubuntu/aws_build #인스턴스에서 파일이 복사되는 경로
    overwrite: yes
hooks:
  ApplicationStop: #이전 프로그램 중지
    - location: stop.sh
  ApplicationStart: #프로그램 실행
    - location: start.sh
      timeout: 60
      runas: root